#!/usr/bin/python
# Copyright (c) 2016 PaddlePaddle Authors. All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Usage: draw.py -m [MONITORFILE] -l [LOGFILE]

draw picture from monitorFile and logFile.

Arguments:
    MONITORFILE             cpu, gpu and memory usage file collected by monitor.sh
    LOGFILE                 training log generated by train.sh 

Options:
    -h      --help
    -m      monitorFile
    -l      logFile

"""

import matplotlib
import matplotlib.pyplot as plt
import re
import sys
from docopt import docopt


def draw_log_info(logFile):
    data = {'AvgCost': []}
    passPos = []
    with open(logFile, 'r') as f:
        batchCounter = 0
        for line in f:
            if "AvgCost" not in line:
                continue
            for attr in data.keys():
                pattern = re.compile(attr + '=([0-9]\.?[0-9]?)', re.S)
                result = re.findall(pattern, line.strip())
                if len(result) == 0:
                    continue
                data[attr].append(float(result[0]))
            if 'Pass' in line:
                pattern = re.compile("Pass=(.*?) ", re.S)
                passNum = re.findall(pattern, line.strip())
                passPos.append(data["AvgCost"][-1])
            batchCounter += 1
        for key in data.keys():
            f = plt.figure()
            plt.plot(range(len(data[key])), data[key])
            f.savefig(key + '.png')
            f = plt.figure()
            plt.plot(range(len(passPos)), passPos)
            f.savefig(key + '_pass.png')


def draw_paddle_usage(monitorFile):
    data = {'memory': [], "gpuMemory": []}
    with open(monitorFile, 'r') as f:
        for line in f:
            if line[0] != "2":
                continue
            lineData = line.strip().split('\t')
            data['memory'].append(int(lineData[3].split('(')[0]))
            data['gpuMemory'].append(int(lineData[4].split()[0]))
        for key in data.keys():
            f = plt.figure()
            plt.plot(range(len(data[key])), data[key])
            f.savefig(key + '.png')


if __name__ == '__main__':
    arguments = docopt(__doc__)
    monitorFile = arguments['MONITORFILE']
    logFile = arguments['LOGFILE']
    draw_log_info(logFile)
    draw_paddle_usage(monitorFile)
